application: frc-notebook
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

handlers:
- url: /_ah/spi/.*
  script: mobile_api.application
- url: /.*
  script: frc_notebook.application

